spring:
  cloud:
    gateway:
      routes:
        - id: articles-read
          uri: lb://textaddict-article-query-api
          predicates:
            - Path=/article-api/articles/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/article-api/(?<segment>.*), /$\{segment}
        - id: articles-write
          uri: lb://textaddict-article-command-api
          predicates:
            - Path=/article-api/articles/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/article-api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: post-user
          uri: lb://textaddict-user-api
          predicates:
            - Path=/user-api/users,/user-api/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-api/(?<segment>.*), /$\{segment}
        - id: user-api
          uri: lb://textaddict-user-api
          predicates:
            - Path=/user-api/users/**
            - Method=GET,PUT,PATCH,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-api-actuator
          uri: lb://textaddict-user-api
          predicates:
            - Path=/user-api/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-api/(?<segment>.*), /$\{segment}
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true